<?php

declare(strict_types=1);

/**
 * Prints the PHP# bridge's `sharp_kind` enum, generated from php-src's `Zend/zend_ast.h`.
 *
 * `just regen-sharp-kinds <path to Zend/zend_ast.h>` writes it to `crates/sharp-bridge/src/kind.rs`.
 */

$path = $argv[1] ?? throw new InvalidArgumentException('Pass the path to php-src\'s `Zend/zend_ast.h`.');
$header = file_get_contents($path);
if ($header === false) {
    throw new RuntimeException("Unable to read {$path}.");
}

$defines = [];
preg_match_all('/^#define (ZEND_AST_\w+_SHIFT)\s+(\d+)$/m', $header, $defines);
$shifts = array_combine($defines[1] ?? [], array_map(intval(...), $defines[2] ?? []));

$enum = [];
preg_match('/enum _zend_ast_kind \{(.*?)\n\};/s', $header, $enum);
$body = $enum[1] ?? throw new RuntimeException('Unable to locate `enum _zend_ast_kind` in the header.');
$body = preg_replace('~/\*.*?\*/|//[^\n]*~s', '', $body) ?? throw new RuntimeException('Unable to strip comments.');

$variants = '';
$value = -1;
foreach (array_filter(array_map(trim(...), explode(',', $body))) as $entry) {
    $kind = [];
    preg_match('/^ZEND_AST_(\w+)(?:\s*=\s*(\d+)\s*<<\s*(\w+))?$/', $entry, $kind);
    $name = $kind[1] ?? throw new RuntimeException("Unable to read the `zend_ast_kind` entry `{$entry}`.");
    $shift = $kind[3] ?? null;
    $value = match ($shift) {
        null => $value + 1,
        default => (int) $kind[2] << ($shifts[$shift] ?? throw new RuntimeException("Unknown shift `{$shift}`.")),
    };

    $variants .= "    SHARP_AST_{$name} = {$value},\n";
}

echo <<<RUST
    //! Generated by `just regen-sharp-kinds` from php-src's `Zend/zend_ast.h`. Do not edit.

    /// One value per `zend_ast_kind`, named as that kind without `ZEND_` and equal to it, so `ext/sharp` casts it.
    #[repr(u16)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum sharp_kind {
    {$variants}}

    RUST;
