<?php

declare(strict_types=1);

/**
 * Prints the PHP# bridge's `sharp_kind` enum, generated from php-src's `Zend/zend_ast.h`, and `SHARP_UNIT_ABI`: the
 * hash of that kind table, the layouts of the compiled file's structs, and the register of PHP# marks in php-sharp's
 * `Zend/zend_compile.h`.
 *
 * `just regen-sharp-kinds <path to Zend/zend_ast.h> <path to Zend/zend_compile.h>` writes it to
 * `crates/sharp-bridge/src/kind.rs`.
 */

$path = $argv[1] ?? throw new InvalidArgumentException('Pass the path to php-src\'s `Zend/zend_ast.h`.');
$header = file_get_contents($path);
if ($header === false) {
    throw new RuntimeException("Unable to read {$path}.");
}

$compilePath = $argv[2] ?? throw new InvalidArgumentException('Pass the path to php-sharp\'s `Zend/zend_compile.h`.');
$compileHeader = file_get_contents($compilePath);
if ($compileHeader === false) {
    throw new RuntimeException("Unable to read {$compilePath}.");
}

$defines = [];
preg_match_all('/^#define (ZEND_AST_\w+_SHIFT)\s+(\d+)$/m', $header, $defines);
$shifts = array_combine($defines[1] ?? [], array_map(intval(...), $defines[2] ?? []));

$enum = [];
preg_match('/enum _zend_ast_kind \{(.*?)\n\};/s', $header, $enum);
$body = $enum[1] ?? throw new RuntimeException('Unable to locate `enum _zend_ast_kind` in the header.');
$body = preg_replace('~/\*.*?\*/|//[^\n]*~s', '', $body) ?? throw new RuntimeException('Unable to strip comments.');

$variants = '';
$value = -1;
foreach (array_filter(array_map(trim(...), explode(',', $body))) as $entry) {
    $kind = [];
    preg_match('/^ZEND_AST_(\w+)(?:\s*=\s*(\d+)\s*<<\s*(\w+))?$/', $entry, $kind);
    $name = $kind[1] ?? throw new RuntimeException("Unable to read the `zend_ast_kind` entry `{$entry}`.");
    $shift = $kind[3] ?? null;
    $value = match ($shift) {
        null => $value + 1,
        default => (int) $kind[2] << ($shifts[$shift] ?? throw new RuntimeException("Unknown shift `{$shift}`.")),
    };

    $variants .= "    SHARP_AST_{$name} = {$value},\n";
}

$layout = '';
$sources = dirname(__DIR__) . '/crates/sharp-bridge/src/';
foreach (['lib.rs' => ['sharp_str', 'sharp_value', 'sharp_node'], 'unit.rs' => ['sharp_unit_header', 'sharp_input']] as $file => $types) {
    $source = file_get_contents($sources . $file);
    if ($source === false) {
        throw new RuntimeException("Unable to read {$sources}{$file}.");
    }

    foreach ($types as $type) {
        $declaration = [];
        preg_match('/(#\[repr\([^)]*\)\])\s*(?:#\[[^\]]*\]\s*)*pub (struct|enum) ' . $type . ' \{(.*?)\n\}/s', $source, $declaration);
        $body = $declaration[3] ?? throw new RuntimeException("Unable to locate `{$type}` in {$file}.");
        $fields = preg_replace(['~//[^\n]*~', '/\s+/'], ['', ' '], $body) ?? throw new RuntimeException("Unable to read `{$type}`.");

        $layout .= "{$declaration[1]} {$declaration[2]} {$type} {" . trim($fields) . "}\n";
    }
}

$register = [];
preg_match('~/\* PHP# marks\n.*?\*/~s', $compileHeader, $register);
$marks = $register[0] ?? throw new RuntimeException('Unable to locate the register of PHP# marks in the header.');
$names = [];
preg_match_all('/^ \* (ZEND_\w+):/m', $marks, $names);
if (($names[1] ?? []) === []) {
    throw new RuntimeException('The register of PHP# marks names no mark.');
}

$marks = (preg_replace('/\s+/', ' ', $marks) ?? throw new RuntimeException('Unable to read the register.')) . "\n";
foreach ($names[1] as $name) {
    $define = [];
    preg_match('/^#define ' . $name . '\s+(.+?)\s*$/m', $compileHeader, $define);
    $marks .= "{$name} " . ($define[1] ?? throw new RuntimeException("Unable to find the value of the mark `{$name}`.")) . "\n";
}

$abi = hash('xxh128', "kinds\0{$variants}\0layout\0{$layout}\0marks\0{$marks}");

echo <<<RUST
    //! Generated by `just regen-sharp-kinds` from php-src's `Zend/zend_ast.h` and php-sharp's `Zend/zend_compile.h`.
    //! Do not edit.

    /// One value per `zend_ast_kind`, named as that kind without `ZEND_` and equal to it, so `ext/sharp` casts it.
    #[repr(u16)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum sharp_kind {
    {$variants}}

    /// The hash of the kind table, the layouts of the compiled file's structs and php-sharp's register of PHP# marks.
    /// An engine reads only a compiled file written for its own value.
    #[allow(clippy::unreadable_literal, clippy::big_endian_bytes)]
    pub const SHARP_UNIT_ABI: [u8; 16] = 0x{$abi}u128.to_be_bytes();

    RUST;
