<?php

declare(strict_types=1);

/**
 * Prints the PHP# bridge's `sharp_kind` enum, generated from php-src's `Zend/zend_ast.h`, one `SHARP_T_<NAME>`
 * constant per php-src token the lowering writes as an attr, read from php-sharp's generated
 * `Zend/zend_language_parser.h`, and `SHARP_UNIT_ABI`: the hash of that kind table, those tokens and the layouts of the
 * compiled file's structs. It hashes no PHP# mark.
 *
 * `just regen-sharp-kinds <path to Zend/zend_ast.h> <path to Zend/zend_language_parser.h>` writes it to
 * `crates/sharp-bridge/src/kind.rs`.
 */

$path = $argv[1] ?? throw new InvalidArgumentException('Pass the path to php-src\'s `Zend/zend_ast.h`.');
$header = file_get_contents($path);
if ($header === false) {
    throw new RuntimeException("Unable to read {$path}.");
}

$parserPath = $argv[2] ?? throw new InvalidArgumentException(
    'Pass the path to php-sharp\'s `Zend/zend_language_parser.h`.',
);
if (count($argv) > 3) {
    throw new InvalidArgumentException(
        'Pass only the paths to php-src\'s `Zend/zend_ast.h` and php-sharp\'s `Zend/zend_language_parser.h`.',
    );
}

$parserHeader = file_get_contents($parserPath);
if ($parserHeader === false) {
    throw new RuntimeException("Unable to read {$parserPath}.");
}

$defines = [];
preg_match_all('/^#define (ZEND_AST_\w+_SHIFT)\s+(\d+)$/m', $header, $defines);
$shifts = array_combine($defines[1] ?? [], array_map(intval(...), $defines[2] ?? []));

$enum = [];
preg_match('/enum _zend_ast_kind \{(.*?)\n\};/s', $header, $enum);
$body = $enum[1] ?? throw new RuntimeException('Unable to locate `enum _zend_ast_kind` in the header.');
$body = preg_replace('~/\*.*?\*/|//[^\n]*~s', '', $body) ?? throw new RuntimeException('Unable to strip comments.');

$variants = '';
$value = -1;
foreach (array_filter(array_map(trim(...), explode(',', $body))) as $entry) {
    $kind = [];
    preg_match('/^ZEND_AST_(\w+)(?:\s*=\s*(\d+)\s*<<\s*(\w+))?$/', $entry, $kind);
    $name = $kind[1] ?? throw new RuntimeException("Unable to read the `zend_ast_kind` entry `{$entry}`.");
    $shift = $kind[3] ?? null;
    $value = match ($shift) {
        null => $value + 1,
        default => (int) $kind[2] << ($shifts[$shift] ?? throw new RuntimeException("Unknown shift `{$shift}`.")),
    };

    $variants .= "    SHARP_AST_{$name} = {$value},\n";
}

$tokens = '';
foreach (['T_FILE'] as $token) {
    $define = [];
    preg_match('/^\s*' . $token . '\s*=\s*(\d+)\b/m', $parserHeader, $define);
    $value = $define[1] ?? throw new RuntimeException("Unable to find the token `{$token}` in {$parserPath}.");

    $tokens .= "pub const SHARP_{$token}: u32 = {$value};\n";
}

$layout = '';
$sources = dirname(__DIR__) . '/crates/sharp-bridge/src/';
foreach ([
    'lib.rs' => ['sharp_str', 'sharp_value', 'sharp_node'],
    'unit.rs' => ['sharp_unit_header', 'sharp_input'],
] as $file => $types) {
    $source = file_get_contents($sources . $file);
    if ($source === false) {
        throw new RuntimeException("Unable to read {$sources}{$file}.");
    }

    foreach ($types as $type) {
        $declaration = [];
        preg_match(
            '/(#\[repr\([^)]*\)\])\s*(?:#\[[^\]]*\]\s*)*pub (struct|enum) ' . $type . ' \{(.*?)\n\}/s',
            $source,
            $declaration,
        );
        $body = $declaration[3] ?? throw new RuntimeException("Unable to locate `{$type}` in {$file}.");
        $fields = preg_replace(['~//[^\n]*~', '/\s+/'], ['', ' '], $body) ?? throw new RuntimeException(
            "Unable to read `{$type}`.",
        );

        $layout .= "{$declaration[1]} {$declaration[2]} {$type} {" . trim($fields) . "}\n";
    }
}

$abi = hash('xxh128', "kinds\0{$variants}\0tokens\0{$tokens}\0layout\0{$layout}");

echo <<<RUST
    //! Generated by `just regen-sharp-kinds` from php-src's `Zend/zend_ast.h` and php-sharp's
    //! `Zend/zend_language_parser.h`.
    //! Do not edit.

    /// One value per `zend_ast_kind`, named as that kind without `ZEND_` and equal to it, so `ext/sharp` casts it.
    #[repr(u16)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum sharp_kind {
    {$variants}}

    // One value per php-src token the lowering writes as an attr, named as that token with `SHARP_` and equal to it,
    // so `ext/sharp` asserts it.
    {$tokens}
    /// The hash of the kind table, the tokens and the layouts of the compiled file's structs.
    /// An engine reads only a compiled file written for its own value.
    #[allow(clippy::unreadable_literal, clippy::big_endian_bytes)]
    pub const SHARP_UNIT_ABI: [u8; 16] = 0x{$abi}u128.to_be_bytes();

    RUST;
